name: Deployment
'on':
  push:
    branches:
      - master
variables: 
  ${{ if or( and( eq('none', parameters.environmentOverride), eq(variables['Build.SourceBranch'], 'refs/heads/develop') ), eq('qa', parameters.environmentOverride) ) }}:
  nodeEnv: 'development'
  angularEnv: 'qa'
  ${{ if or( and( eq('none', parameters.environmentOverride), eq(variables['Build.SourceBranch'], 'refs/heads/release/beta') ), eq('beta', parameters.environmentOverride) ) }}:
    nodeEnv: 'production'    
    angularEnv: 'beta'
  ${{ if or( and( eq('none', parameters.environmentOverride), eq(variables['Build.SourceBranch'], 'refs/heads/master') ), eq('prod', parameters.environmentOverride) ) }}:
    nodeEnv: 'production'
    angularEnv: 'production'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
        env: 
          NODE_ENV: $(nodeEnv)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Deploy via angular-cli-ghpages
        run: npm run deploy:prod
        run: echo ${{env}}
        env:
          NODE_ENV: $(nodeEnv)
          AIRTABLE_API_KEY_READ: ${{ secrets.AIRTABLE_API_KEY_READ }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}