name: Build & Deployment
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Generate .env
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'NODE_ENV' # [Required]
          value: ${{secrets.NODE_ENV_PROD}} # [Required]
          default: 'production' # [Optional] if `value` is empty, this is used instead
      - name: Build
        run: npm run build:prod
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Generate .env
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'NODE_ENV' # [Required]
          value: ${{secrets.NODE_ENV_PROD}} # [Required]
          default: 'production' # [Optional] if `value` is empty, this is used instead
      - name: Deploy via angular-cli-ghpages
        run: npm run deploy:prod
        env:
          AIRTABLE_API_KEY_READ: ${{ secrets.AIRTABLE_API_KEY_READ }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}